### PR TITLE
fix a few typos

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Comment by bartyrealms** [comment]
necessary

**Comment by ajanata** [comment]
Please stop spamming approvals or I'll have to ban you.

**Comment by kashike** [comment]
Sorry about my friend, he was being silly. I've encounted another typo and have added another commit to fix it.

**Comment by kashike** [comment]
@ajanata Do you have any plans to merge this, or can I close this pull request?

**Comment by devgianlu** [comment]
See https://github.com/ajanata/PretendYoureXyzzy/pull/230#issuecomment-607365589

**Pull request closed without merging**
