### PR TITLE
Add CORS support

### LINKED ISSUE #122: Add CORS to the API
The API is pretty much unusable now, as there is no CORS on it. It is therefore impossible to create a client in the browser (without owning your domain), since the Ajax same-origin policy breaks it. Obviously, you could just proxy the requests through another server, but that would break your sessions (since they seem to be tied to IPs), and IP banning... need I say more?

It only takes one HTTP header to enable it. I don't have any JSP/Tomcat/whatever experience, but it should be very easy to implement.

### PR DESCRIPTION
**Pull request by Voltasalt**
This will close #122, and allow other domains to access this API. (So it's possible to make browser clients)

### CODE REVIEW

**Comment by Voltasalt** [comment]
Bump?

**Comment by ajanata** [comment]
I know this is super old (sorry!) but I'm getting startup errors. I'm going to pull this out as I don't have the cycles to investigate right now.

Tomcat is just ... not starting properly, and Jetty is outright saying it can't find it.

Apr 03, 2016 10:16:30 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error filterStart
Apr 03, 2016 10:16:30 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/zy] startup failed due to previous errors

**Comment by jdf221** [comment]
Any update on this?

I don't get any errors when running it.

**Comment by ajanata** [comment]
I'm not getting errors on a freshly re-installed server, but it's causing Chrome to refuse to work with it via HTTPS (because Chrome sends Origin: for every request, and Tomcat sees that and doesn't like the fact that it sees 'https' on a connection that (to it) was http, as far as I can tell). I've spent more time than I want to fighting with this. I'm going to have to pass on this for now.

**Pull request merged**
